<div class="cnkt-main">
   <div class="group">
      <p><?php _e('Copy and paste the following WP_Query into a <a href="http://codex.wordpress.org/Theme_Development#Template_Files" target="_blank">PHP template</a> within your WordPress theme.', EWPQ_NAME); ?></p>
      <textarea id="query-output"></textarea>
   </div>
</div>
<div class="cnkt-sidebar">
   <div class="cta">
      <h3><?php _e('Save Your Query', EWPQ_NAME); ?></h3>
      <div class="cta-wrap save-query-wrap">
	      <label for="ewpq_query_alias-alias">Query Alias</label>
	      <input type="text" id="ewpq_query_alias" class="ewpq_query_alias" value="" autocomplete="off" placeholder="<?php _e('Enter a query alias', EWPQ_NAME); ?>">
         <button type="button" class="cnkt-btn lg" id="ewpq-save-query" style="margin: 0;"><i class="fa fa-download"></i> &nbsp;<?php _e('Save Query', EWPQ_NAME); ?></button>
         <div class="saving"></div>
         <div class="saved-response-text"></div>
         <div class="cover">
            <span>Save, edit and delete past queries with <a href="https://connekthq.com/plugins/easy-query/pro/" target="_parent">Easy Query Pro</a></span>
         </div>
      </div>
   </div>
   <div class="cta">
      <h3><?php _e('About Your Query', EWPQ_NAME); ?></h3>
      <div class="cta-wrap">
         <p><?php _e('This WP_Query has been generated by the selected parameters on the Query Builder page. To make adjustments to this query you should return to the Query Builder.', EWPQ_NAME); ?></p>
      </div>
   </div>
</div>